# Generated by Django 4.2.5 on 2023-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='defaultpic.jpg', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
