# Generated by Django 4.2.5 on 2023-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_customuser_profilepic_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='file',
            field=models.FileField(upload_to='inbox'),
        ),
    ]
