# Generated by Django 4.2.5 on 2023-10-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_fileshare_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
